Feature/61
openworm/org.geppetto.python pull request #62
Opened 2020-07-01 13:26 UTC by rodriguez-facundo

Add get_credentials to dataSourceService for password protected db

2020-07-01 15:39 UTC, rodriguez-facundo commented
@filippomc

2020-07-03 07:48 UTC, filippomc commented on pygeppetto/model/datasources/datasources.py
> +    auth = EAttribute(eType=EString, derived=False, changeable=True)
@rodriguez-facundo this is not a change we can make here as this code is automatically generated from the ecore specification.  Usually those changes are made by @tarelli in the Java side.

2020-07-03 08:02 UTC, filippomc requested changes
@rodriguez-facundo the approach looks good and the code is clean. 
Before really committing that to pygeppetto we must be sure that there are no other ways already to use credentials we overlooked and implement this if needed through the ecore specification.

2020-07-03 13:23 UTC, filippomc commented
@facundo we just need to replace the file geppettoModel.ecore with this https://github.com/openworm/org.geppetto.model/blob/de10cc313f4e79b37e2385266f630cd16dd58a6c/src/main/resources/geppettoModel.ecore , then we are ready to merge and we'll release pygeppetto 0.8.1 with your changes. cc @tarelli

2020-07-03 13:54 UTC, rodriguez-facundo commented
@filippomc updated

2020-07-03 14:26 UTC, filippomc approved these changes

2020-07-03 14:26 UTC, merged